// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ECGFScpp
SEXP ECGFScpp(const arma::colvec g, const arma::colvec mu, const double t, const arma::colvec y);
RcppExport SEXP _Saddlepoint_ECGFScpp(SEXP gSEXP, SEXP muSEXP, SEXP tSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ECGFScpp(g, mu, t, y));
    return rcpp_result_gen;
END_RCPP
}
// dECGFScpp
SEXP dECGFScpp(const arma::colvec g, const arma::colvec mu, const double t, const arma::colvec y);
RcppExport SEXP _Saddlepoint_dECGFScpp(SEXP gSEXP, SEXP muSEXP, SEXP tSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dECGFScpp(g, mu, t, y));
    return rcpp_result_gen;
END_RCPP
}
// ddECGFScpp
SEXP ddECGFScpp(const arma::colvec g, const arma::colvec mu, const double t, const arma::colvec y);
RcppExport SEXP _Saddlepoint_ddECGFScpp(SEXP gSEXP, SEXP muSEXP, SEXP tSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ddECGFScpp(g, mu, t, y));
    return rcpp_result_gen;
END_RCPP
}
// GenoResid
SEXP GenoResid(const arma::colvec g, const arma::mat x);
RcppExport SEXP _Saddlepoint_GenoResid(SEXP gSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(GenoResid(g, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Saddlepoint_ECGFScpp", (DL_FUNC) &_Saddlepoint_ECGFScpp, 4},
    {"_Saddlepoint_dECGFScpp", (DL_FUNC) &_Saddlepoint_dECGFScpp, 4},
    {"_Saddlepoint_ddECGFScpp", (DL_FUNC) &_Saddlepoint_ddECGFScpp, 4},
    {"_Saddlepoint_GenoResid", (DL_FUNC) &_Saddlepoint_GenoResid, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Saddlepoint(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
