# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Score ECGF
#' 
#' Evaluate \eqn{K_{n}^{S}(t)}.
#' 
#' @param g Genotype.
#' @param mu Mean of Y under the null.
#' @param t Evaluation point.
#' @param y Phenotype.
#' @return Numeric evaluation.
ECGFScpp <- function(g, mu, t, y) {
    .Call(`_Saddlepoint_ECGFScpp`, g, mu, t, y)
}

#' First Derivative of Score ECGF
#' 
#' Evaluate \eqn{\dot{K}_{n}^{S}(t)}.
#' 
#' @param g Genotype.
#' @param mu Mean of Y under the null.
#' @param t Evaluation point.
#' @param y Phenotype.
#' @return Numeric evaluation.
dECGFScpp <- function(g, mu, t, y) {
    .Call(`_Saddlepoint_dECGFScpp`, g, mu, t, y)
}

#' Second Derivative of Score ECGF
#' 
#' Evaluate \eqn{\ddot{K}_{n}^{S}(t)}.
#' 
#' @param g Genotype.
#' @param mu Mean of Y under the null.
#' @param t Evaluation point.
#' @param y Phenotype.
#' @return Numeric evaluation.
ddECGFScpp <- function(g, mu, t, y) {
    .Call(`_Saddlepoint_ddECGFScpp`, g, mu, t, y)
}

#' Genotypic Residual
#' 
#' Residualize genotype with respect to covariates.
#' 
#' @param g Genotype.
#' @param x Covariates.
#' @return Numeric evaluation.
#' @export
GenoResid <- function(g, x) {
    .Call(`_Saddlepoint_GenoResid`, g, x)
}

